[TOC]

# 1. Promise

​	所谓 `Promise` ，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。

​	有三种状态：`pending(进行中)` 、 `fulfilled(已完成)`（一般使用 `resolve` 表示） 和 `reject(已失败)` 。状态的改变只有两种可能：`pending -> fulfilled` 和 `pending -> reject` 。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。如果改变已经发生了，你再对`Promise`对象添加回调函数，也会立即得到这个结果。

​	缺点：Promise 内部抛出的错误不会反应到外部；处于pending状态时无法判断具体到哪一个阶段。如果某些事件不断发生，一般来说使用 Stream 模式。

## 1.0 基本用法

### 1. Resolve & Reject 回调函数

```js
// 必须通过 resolve 或 reject 传递参数，不然不会跳出
// 
const promise = new Promise((resolve, reject) => {
  if(...) {
		resolve(); // 相当于正常return
  } else {
		reject(); // 相当于throw new Error();
	}
})
```

​	`resolve` 函数的参数除了正常的值外，还可能是另一个 Promise 实例。

```js
// p1
let p1 = new Promise((resolve, reject) => { ... })
// p2
let p2 = new Promise((resolve, reject) => {
  // 如果p1的状态已经是resolved或rejected, 那么p2的回调函数会立即执行
  resolve(p1);
})
```

### 2. then() & catch() 处理

```js
promise
.then(() => {
  // 此处处理 resolve()
  console.log('resolve-data')
})
.catch(() => {
  // 此处处理 reject()
  console.log('reject-data')
})
```

### 3. 执行顺序

1. Promise 新建后就会立即执行，内部的代码最先输出
2. 在当前脚本的所有同步任务其次执行
3. 最后执行 Promise 的回调函数
4. setTimeout在下一轮的开始执行（或者可以理解成本轮最最最最最最后执行）

```js
setTimeout(() => {
  console.log('4. 下一轮的开始执行');
}, 0)

let promise = new Promise((resolve, reject) => {
  console.log('1. promise立即执行');
  resolve();
  console.log('1.1 resolve不会停止promise')
  throw new Error('error'); // 不会抛出，因为状态已经是resolved了，不会变成reject
})

promise.then(() => {
  console.log('3. 回调函数最后执行');
})

console.log('2. 同步任务在promise之后执行')

// 1. promise立即执行
// 1.1 resolve不会停止promise
// 2. 同步任务在promise之后执行
// 3. 回调函数最后执行
// 4. 下一轮的开始执行
```

****



## 1.1 .then() / .catch() / .finally()

### 1. promise.prototype.then()

​	关于两个回调函数：

```js
// .then()可接收两个参数, 第一个参数是resolve的回调函数, 第二个参数reject的回调函数
promise.then(() => {
  // 处理resolve
}, () => {
  // 处理reject
})
```

​	`then` 方法返回的是一个新的 `Promise` 实例（注意，不是原来那个 `Promise` 实例）。因此可以采用链式写法，即 `then` 方法后面再调用另一个`then`方法。 => 执行完 `.then` 后成为一个新的promise对象。

```js
// 链式
promise.then(() => { }).then((res) => {...}, (err) => {...})
```

### 2. promise.prototype.catch()

​	一般 `reject` 的回调函数作为 `.then()` 的第二个参数。 `.catch()` 专门用来处理 `reject` ，等于 `.then(null, rejection)` ｜ `.then(undefined, rejection)` 。

```js
// reject的回调函数一般作为 `.then()` 的第二个参数
// .then(null, () => {...})
// .then(undefined, () => {...})
// .catch是处理reject回调函数的别名
// .catch(() => {...}) 
```

:exclamation:使用 `.catch()` 可以捕获前面抛出的错误(**顺着链**遇到.catch捕获前面所有的错误)，但使用 `.then(null|undefined, rejection)` 就不能捕获。 

****

### 3. promise.prototype.finally()

​	`.finally()` 方法的回调函数不接受任何参数。不管 `promise` 最后的状态，在执行完 `then` 或 `catch` 指定的回调函数以后，都会执行 `finally` 方法指定的回调函数。

```js
promise
  .then(() => {...})
	.catch(() => {...})
  .finally(() => {...})
```

****



## 1.2 all() / race() / any() / allSelected()

​	四个方法都接受一个数组作为参数，e.g. `const p = Promise.all([p1, p2, p3])`。

```js
// 接受数组, 成员必须为Promise对象, 非Promise直接resolve为Promise
const p = Promise.all([p1, p2, p3]);

// 可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。
```

1. `all()` ：全部resolved才返回resolved，但凡有rejected则返回rejected。
2. `race()` ：第一个状态改变的作为结果。
3. `any()` ：全部rejected才返回rejected，但凡有resolved则返回resolved。
4. `allSelected()`：

### 1. Promise.all()

```js
// p1, p2, p3 都是resolved状态，把p1, p2, p3的返回值作为数组传递给.then()
p.then(([v1, v2, v3]) => { ... }) // 此处数组解构

// p1, p2, p3 任何一个被rejected, 把第一个被reject的返回值传递给.catch()
p.catch((rejection) => { ... })
```

:exclamation:作为参数的 Promise 实例定义了 `.catch()` 会阻碍触发 `Promise.all().catch()` 。

> e.g. `p2` 如果自己定义了 catch 方法，那么就会执行本身的回调，执行完之后返回一个新的 Promise 实例，该实例执行完了 catch 方法之后也会变成 `resolved` 。因此最后会执行 `Promise.all().then()` 。

### 2. Promise.race()

​	只要 `p1` 、 `p2` 、 `p3` 之中有一个实例率先改变状态， `p` 的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给 `p` 的回调函数。

```js
// 可以用来实现 n 秒内无法···则···
const err = new Promise(() => {
  setTimeout(() => reject(new Error('request timeout')), 5000);
})
const p = Promise.race([fetch('/resource'), err])

p
.then({
  // 处理5s内fetch成功的事件
})
.catch({
  // 处理5s内未fetch, timeout事件
})
```

### 3. Promise.any()

```js
// p1, p2, p3 任何一个实例resolved，把其返回值作为传递给.then()
p.then(([v1, v2, v3]) => { ... }) // 此处数组解构

// p1, p2, p3 都是rejected, 把p1, p2, p3的返回值作为数组传递给.catch()
p.catch((rejection) => { ... })
```

### 4. Promise.allSelected()

​	`Promise.allSelected()` 用来确定一组异步操作是否都结束了（不管成功或失败）。

```js
// 把p1, p2, p3的 {状态, 值} 形成数组传递给.then()

// 针对resolve和reject的两种情况分别会返回对象:
[
  { status: 'fulfilled', value: ${resolved-value} },
  { status: 'rejected', reason: ${rejected-value}}
]
```

## ? 1.3 Promise.try

****

# 2. Async & Await

参考：[ES6 - Aysnc](https://es6.ruanyifeng.com/#docs/async)、[理解 JavaScript 的 async/await](https://segmentfault.com/a/1190000007535316)。

:exclamation:**NOTE:** `async/await` is part of ECMAScript 2017 and is not supported in Internet Explorer and older browsers, so use with caution.

### 2.1 async

​	async 函数返回的是一个 **Promise 对象**。如果在函数中 `return` 一个直接量，async 会把这个直接量通过 `Promise.resolve()` 封装成 Promise 对象。

​	异步体现在：一旦遇到 `await` 就会先返回（执行函数外的其他代码），等到异步操作完成，再接着执行函数体内后面的语句。

```js
async function test() {
  // 封装成 Promise 对象返回
  return 'resolved-data'; // 变成resolved
  
  // throw new Error(); // 变成rejected
}

// 等价于在内部手动创建一个 Promise 对象返回
// 本质上就是Promise的语法糖
function test() {
  return new Promise(resolve => {
    resolve('resolved-data');
  })
}

// 可以直接对async函数的返回结果使用.then()
test().then((v) => console.log(v)); // resolved-data
```

### 2.2 await

​	await 实际就是 `async wait` ，等待一个 Promise 对象的返回并且接受其 resolved 的值。即 await 函数返回的是一个值（不是 Promise对象，而是 resolved 的值）。

```js
async testAsync() {
  // await一个非async函数，则直接按照寻常同步函数返回赋值
  let value = await getNotAsync(); // value
  function getNotAsync() {
    return "value";
  }
  
  // await一个async函数，则赋值resolved的值
  // 在未等到该async函数的返回前，阻塞本函数
  let result = await getAsync(); // result
  async function getAsync() {
    return "result";
  }
}
```

### 2.3 await 异常及 try-catch

​	所谓 await 异常指的是等待的 Promise 对象的状态变为 rejected。任何一个 `await` 语句后面的 Promise 对象变为 `reject` 状态，那么整个 `async` 函数都会中断执行。

```js
// 1. 可以在await的Promise对象后补充catch方法防止中断
async test() {
  await Promise.reject('error').catch( e => console.log(e) );
  // 不会中断函数（执行了catch），下面的依然会执行
  return await Promise.resolve('return successfully!');
}

// 2. 使用try-catch，和上面的方法等效
async test() {
  try{
    await Promise.reject('error');
  } catch(e) {
    console.log(e);
  }
  return await Promise.resolve('return successfully!');
}
```

### 2.4 why `async` ?

​	代码更清晰，更像同步代码风格。

```js
// async 的作用实际等于链式的.then()
// 1. 链式Promise
step1.then().then().then().then()

// 2. async
async function do() {
  const time = 0;
  const time1 = await step1(time);
  const time2 = await step2(time1);
  const time3 = await step3(time2);
  console.log(`result is ${time3}`);
}
```

### 2.5 注意点

1. `await` 只能放在 `async` 函数内， 否则报错。

2. 使用 `try-catch` 或 `Promise.prototype.cath()`  处理异常 `rejected` 状态。

3. 互不依赖的两个独立的异步操作最好不要写成继发关系（即一个执行完了才执行另一个）。

```js
// 继发
let foo = await getFoo();
let bar = await getBar();

// 同时触发
// 写法一：
let [foo, bar] = await Promise.all([getFoo(), getBar()]);
// 写法二：
let fooPromise = getFoo(),
    barPromise = getBar();
let foo = await fooPromise,
    bar = await barPromise;
```

4. 注意 `forEach` 引发并发await，可能会得到错误的结果。

```js
let docs = [{}, {}, {}];

// 并发可能得到错误的结果
docs.forEach(async function(doc) {
  await db.post(doc);
})

// 继发
for(let doc of docs) {
  await db.post(doc);
}
```

5. 可以使用 `Promise.all()` 处理并发。

```js
async function dbFuc(db) {
  let docs = [{}, {}, {}];
  let promises = docs.map((doc) => db.post(doc));

  let results = await Promise.all(promises);
  console.log(results);
}
```

